services:
  db:
    image: postgres:16-alpine
    container_name: obelisk-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: obelisk
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./certs:/app/certs:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d obelisk"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: obelisk-redis
    restart: unless-stopped
    ports:
      - "6380:6379"

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 3s

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: obelisk-frontend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"
      - "3443:3443"
    volumes:
      - ./frontend:/app
      - frontend_bun_cache:/home/bun/.bun/install/cache
      - ./certs:/app/certs:ro
    environment:
      NODE_ENV: production
      BETTER_AUTH_URL: $BETTER_AUTH_URL
      BETTER_AUTH_SECRET: $BETTER_AUTH_SECRET
      BETTER_AUTH_DATABASE_URL: $BETTER_AUTH_DATABASE_URL
      DATABASE_URL: $DATABASE_URL
      API_KEY: $API_KEY
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      
    depends_on:
      db:
        condition: service_healthy
      websockets:
        condition: service_started
      redis:
        condition: service_healthy

  websockets:
    build:
      context: .
      dockerfile: ./websockets/Dockerfile
    container_name: obelisk-websockets
    restart: unless-stopped
    working_dir: /app
    stdin_open: true
    tty: true
    command: >
      sh -c "
      bun install --ignore-scripts &&
      bun run server.js
      "
    ports:
      - "4001:4001"
    volumes:
      - ./websockets:/app
      - ./packages:/packages
      - backend_bun_cache:/home/bun/.bun/install/cache
      - ./certs:/app/certs:ro
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/obelisk
      PORT: 4001
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  frontend_bun_cache:
  backend_bun_cache:
